"""add users table

Revision ID: 5fcdc83010c7
Revises: a80218d45459
Create Date: 2026-02-05 13:58:26.893377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fcdc83010c7'
down_revision: Union[str, None] = 'a80218d45459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('delete', sa.Boolean(), nullable=False))
    op.drop_index('ix_users_is_anonymous', table_name='users')
    op.create_index(op.f('ix_users_delete'), 'users', ['delete'], unique=False)
    op.drop_column('users', 'is_anonymous')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_anonymous', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_delete'), table_name='users')
    op.create_index('ix_users_is_anonymous', 'users', ['is_anonymous'], unique=False)
    op.drop_column('users', 'delete')
    # ### end Alembic commands ###
