"""rename sessions to usersessions

Revision ID: 8d321bcbc0ef
Revises: 5fcdc83010c7
Create Date: 2026-02-06 13:00:26.756934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d321bcbc0ef'
down_revision: Union[str, None] = '5fcdc83010c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Enable pgcrypto extension if not exists
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    
    # First: Add new columns to users table WITHOUT the constraint
    op.add_column('users', sa.Column('user_id', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('encrypted_username', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('verification_hash', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('encryption_key_salt', sa.Text(), nullable=True))
    
    # Update existing rows with generated values
    # Generate user_id from existing id using substring of MD5
    op.execute("""
        UPDATE users 
        SET user_id = SUBSTRING(MD5(id::text || random()::text) FROM 1 FOR 16),
            encrypted_username = '',
            verification_hash = '',
            encryption_key_salt = ''
    """)
    
    # Now make the columns NOT NULL
    op.alter_column('users', 'user_id', nullable=False)
    op.alter_column('users', 'encrypted_username', nullable=False)
    op.alter_column('users', 'verification_hash', nullable=False)
    op.alter_column('users', 'encryption_key_salt', nullable=False)
    
    # Create unique index on user_id
    op.create_index('uq_users_user_id', 'users', ['user_id'], unique=True)
    
    # Now create other tables
    op.create_table('config',
    sa.Column('config_key', sa.String(length=50), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('config_key')
    )
    
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('encryption_key_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_expiry', 'sessions', ['expires_at'], unique=False)
    
    # Drop old tables first
    op.drop_index('ix_media_message_id', table_name='media')
    op.drop_table('media')
    op.drop_table('message_receipts')
    op.drop_table('chats')
    op.drop_table('chat_participants')
    op.drop_table('contacts')
    
    # Now modify messages table
    # First add new columns as nullable
    op.add_column('messages', sa.Column('message_id', sa.String(length=16), nullable=True))
    op.add_column('messages', sa.Column('recipient_id', sa.String(length=16), nullable=True))
    op.add_column('messages', sa.Column('encrypted_content', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('encrypted_metadata', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('read_status', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('thread_id', sa.String(length=16), nullable=True))
    
    # Generate message_id for existing messages using MD5
    op.execute("""
        UPDATE messages 
        SET message_id = SUBSTRING(MD5(id::text || random()::text) FROM 1 FOR 16),
            encrypted_content = COALESCE(content, ''),
            timestamp = COALESCE(created_at, NOW()),
            read_status = false
    """)
    
    # TEMPORARY: Set recipient_id to a valid user_id
    # First, get a valid user_id
    op.execute("""
        WITH first_user AS (
            SELECT user_id FROM users LIMIT 1
        )
        UPDATE messages 
        SET recipient_id = (SELECT user_id FROM first_user)
        WHERE recipient_id IS NULL
    """)
    
    # Now make columns NOT NULL
    op.alter_column('messages', 'message_id', nullable=False)
    op.alter_column('messages', 'recipient_id', nullable=False)
    op.alter_column('messages', 'encrypted_content', nullable=False)
    op.alter_column('messages', 'timestamp', nullable=False)
    op.alter_column('messages', 'read_status', nullable=False)
    
    # Create the conversations table AFTER we have messages updated
    op.create_table('conversations',
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('other_user_id', sa.String(length=16), nullable=False),
    sa.Column('last_message_id', sa.String(length=16), nullable=True),
    sa.Column('last_message_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('encrypted_summary', sa.Text(), nullable=True),
    sa.CheckConstraint('user_id != other_user_id', name='check_different_conversation_users'),
    sa.ForeignKeyConstraint(['other_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'other_user_id')
    )
    op.create_index('idx_recent', 'conversations', ['user_id', 'last_message_timestamp'], unique=False)
    
    # Drop old foreign keys
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey', cascade=True)
    op.drop_constraint('messages_reply_to_fkey', 'messages', type_='foreignkey', cascade=True)
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey', cascade=True)
    
    # Temporarily change sender_id to text to match user_id
    # First, create a temporary column
    op.add_column('messages', sa.Column('temp_sender_id', sa.String(length=16), nullable=True))
    
    # Map old UUID sender_id to new user_id
    op.execute("""
        UPDATE messages m
        SET temp_sender_id = u.user_id
        FROM users u
        WHERE u.id = m.sender_id
    """)
    
    # Drop old sender_id column and rename temp column
    op.drop_column('messages', 'sender_id')
    op.alter_column('messages', 'temp_sender_id', new_column_name='sender_id')
    
    # Create new foreign keys
    op.create_foreign_key('fk_messages_sender_id', 'messages', 'users', ['sender_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_messages_recipient_id', 'messages', 'users', ['recipient_id'], ['user_id'], ondelete='CASCADE')
    
    # Create indexes
    op.drop_index('idx_chat_created', table_name='messages')
    op.drop_index('ix_messages_chat_id', table_name='messages')
    op.create_index('idx_conversation', 'messages', ['sender_id', 'recipient_id', 'timestamp'], unique=False)
    op.create_index('idx_unread', 'messages', ['recipient_id', 'read_status'], unique=False)
    
    # Drop old columns
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'reply_to')
    op.drop_column('messages', 'type')
    op.drop_column('messages', 'chat_id')
    op.drop_column('messages', 'edited_at')
    op.drop_column('messages', 'id')
    op.drop_column('messages', 'content')
    op.drop_column('messages', 'deleted_at')
    
    # Remove old columns from users
    op.drop_index('ix_users_delete', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'public_key')
    op.drop_column('users', 'delete')
    op.drop_column('users', 'username')
    
    # Finally, handle the id column - drop it if it exists
    op.execute("""
        DO $$ 
        BEGIN 
            IF EXISTS (SELECT 1 FROM information_schema.columns 
                      WHERE table_name='users' AND column_name='id') THEN
                ALTER TABLE users DROP COLUMN id;
            END IF;
        END $$;
    """)
    
    # Set user_id as primary key
    op.execute('ALTER TABLE users DROP CONSTRAINT IF EXISTS users_pkey')
    op.create_primary_key('users_pkey', 'users', ['user_id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('delete', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('public_key', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_delete', 'users', ['delete'], unique=False)
    op.drop_column('users', 'encryption_key_salt')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'verification_hash')
    op.drop_column('users', 'encrypted_username')
    op.drop_column('users', 'user_id')
    op.add_column('messages', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('edited_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('type', postgresql.ENUM('TEXT', 'IMAGE', 'VIDEO', 'AUDIO', 'FILE', name='messagetype'), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('reply_to', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('messages_reply_to_fkey', 'messages', 'messages', ['reply_to'], ['id'])
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_unread', table_name='messages')
    op.drop_index('idx_conversation', table_name='messages')
    op.create_index('ix_messages_chat_id', 'messages', ['chat_id'], unique=False)
    op.create_index('idx_chat_created', 'messages', ['chat_id', 'created_at'], unique=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.String(length=16),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('messages', 'thread_id')
    op.drop_column('messages', 'read_status')
    op.drop_column('messages', 'timestamp')
    op.drop_column('messages', 'encrypted_metadata')
    op.drop_column('messages', 'encrypted_content')
    op.drop_column('messages', 'recipient_id')
    op.drop_column('messages', 'message_id')
    op.create_table('contacts',
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('contact_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('blocked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.CheckConstraint('owner_id <> contact_user_id', name='check_self_contact'),
    sa.ForeignKeyConstraint(['contact_user_id'], ['users.id'], name='contacts_contact_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='contacts_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_id', 'contact_user_id', name='contacts_pkey')
    )
    op.create_table('chat_participants',
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'MEMBER', name='participantrole'), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('left_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name='chat_participants_chat_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chat_participants_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'user_id', name='chat_participants_pkey')
    )
    op.create_table('chats',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('DIRECT', 'GROUP', name='chattype'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("type = ANY (ARRAY['DIRECT'::chattype, 'GROUP'::chattype])", name='check_chat_type'),
    sa.PrimaryKeyConstraint('id', name='chats_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('message_receipts',
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('SENT', 'DELIVERED', 'READ', name='receiptstatus'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint("status = ANY (ARRAY['SENT'::receiptstatus, 'DELIVERED'::receiptstatus, 'READ'::receiptstatus])", name='check_receipt_status'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='message_receipts_message_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='message_receipts_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id', name='message_receipts_pkey')
    )
    op.create_table('media',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('size', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='media_message_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='media_pkey')
    )
    op.create_index('ix_media_message_id', 'media', ['message_id'], unique=False)
    op.drop_index('idx_expiry', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_recent', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('config')
    # ### end Alembic commands ###
