"""add is_anonymous to users

Revision ID: a80218d45459
Revises: 0a8aab4ed096
Create Date: 2026-01-30 14:30:42.430316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80218d45459'
down_revision: Union[str, None] = '0a8aab4ed096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_anonymous', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_is_anonymous'), 'users', ['is_anonymous'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_anonymous'), table_name='users')
    op.drop_column('users', 'is_anonymous')
    # ### end Alembic commands ###
